// vue/src/components/Messages/messageForm.vue
<template>
  <form v-on:submit="postMessage">
    <input v-model="text" />
    <button type="submit">Post</button>
  </form>
</template>

<script>
export default {
  data () {
    return {
      text: ''
    }
  },
  methods: {
    postMessage (ev) {
      ev.preventDefault()
      this.$emit('message', { text: this.text })
    }
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
</style>

// react-proj/src/components/messageForm.jsx

import React, { Component } from 'react';

export class MessageForm extends Component {
  state = {
    text: ''
  }

  _onSubmit = (ev) => {
    let { postMessage } = this.props;
    postMessage({
      text: this.state.text
    })
    ev.preventDefault()
  }

  _onChange = (ev) => {
    let text = ev.target.value
    this.setState(prev => ({
      ...prev,
      text
    }))
  }

  render() {
    return (
    <form onSubmit={this._onSubmit} >
      <input name="text" value={this.state.text} onChange={this._onChange} />
      <button type="submit">Post</button>
    </form>
    )
  }
}
